apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-calci
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness-calci
  template:
    metadata:
      labels:
        app: harness-calci
    spec:
      containers:
      - name: app
        image: pavandath510/calci:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: harness-calci-app-service
  namespace: default
spec:
  selector:
    app: harness-calci
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
